---
- name: Update Webservers, NFS Server, and Database Server
  hosts: webservers, nfs, db
  become: yes
  tasks:
    - name: Ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest
   

- name: Update The LoadBalancer Server
  hosts: lb
  become: yes
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: Ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest